export const SESSION_LOADED = 'SESSION_LOADED';
export type SESSION_LOADED = typeof SESSION_LOADED;

export const LOGIN_DATA_RECEIVED = 'LOGIN_DATA_RECEIVED';
export type LOGIN_DATA_RECEIVED = typeof LOGIN_DATA_RECEIVED;

export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export type LOGIN_REQUESTED = typeof LOGIN_REQUESTED;
