export const SESSION_LOADED = 'SESSION_LOADED';
export type SESSION_LOADED = typeof SESSION_LOADED;
export const LOGOUT_REQUESTED = 'LOGOUT_REQUESTED';
export type LOGOUT_REQUESTED = typeof LOGOUT_REQUESTED;
export const LOGIN_DATA_RECEIVED = 'LOGIN_DATA_RECEIVED';
export type LOGIN_DATA_RECEIVED = typeof LOGIN_DATA_RECEIVED;
export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export type LOGIN_REQUESTED = typeof LOGIN_REQUESTED;

export const TRANSACTION_SEARCH_REQUESTED = 'TRANSACTION_SEARCH_REQUESTED';
export type TRANSACTION_SEARCH_REQUESTED = typeof TRANSACTION_SEARCH_REQUESTED;
export const TRANSACTION_SEARCH_CLEAR = 'TRANSACTION_SEARCH_CLEAR';
export type TRANSACTION_SEARCH_CLEAR = typeof TRANSACTION_SEARCH_CLEAR;